### ISSUE TITLE
Grid sizes consisent

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/intro-curriculum#15]
For this repo, we will only ever have 10 posts (at least in the near term). So, we can probably do a little more work to make those 10 posts look nice on the grid page:

http://dev-owi.usgs.gov-website.s3-website-us-west-2.amazonaws.com/R/intro-curriculum/

I've vote they are all the same size. Much shorter. I'll leave it up to @mwernimont to figure out specifics.

**Comment by lindsaycarr** [comment]
Closed by #23
