### ISSUE TITLE
Special icons

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/intro-curriculum#16]
It would be pretty sweet to have special icons for each grid here:

http://dev-owi.usgs.gov-website.s3-website-us-west-2.amazonaws.com/R/intro-curriculum/

The topics are:

1. Introduction
2. Get
3. Clean
4. Explore
5. Analyze
6. Analyze II
7. Visualize
8. Visualize II
9. Repeat-ability
10. Parting Thoughts

I'd vote #1 is our USGS-R icon, maybe #10 too. But after that, I'd love to see if @mwernimont could come up with something nice and clean.

**Comment by mwernimont** [comment]
![intro-1](https://cloud.githubusercontent.com/assets/6390096/16989008/09361cc0-4e58-11e6-8349-0e23ab1a426e.jpg)
![intro-2](https://cloud.githubusercontent.com/assets/6390096/16989006/0930ac9a-4e58-11e6-9ca1-1afa889d2f61.jpg)
![intro-3](https://cloud.githubusercontent.com/assets/6390096/16989007/0931bb58-4e58-11e6-9017-9f4e96df3b2e.jpg)

**Comment by mwernimont** [comment]
@lindsaycarr @ldecicco-USGS @jread-usgs Looking for feedback and suggestions

**Comment by jread-usgs** [comment]
Cool!

For the `ggplot2` one, I think you should just re-style the base one:

![image](https://cloud.githubusercontent.com/assets/2349007/16989220/f3242c46-4e58-11e6-9118-53757ec64a25.png)

**Comment by jread-usgs** [comment]
This is what ggplot graphs tend to look like by default:
![image](https://cloud.githubusercontent.com/assets/2349007/16989247/0dea39bc-4e59-11e6-9642-68bcb27b66ba.png)

**Comment by lindsaycarr** [comment]
Only one I am not a huge fan of is the microscope - wondering if we can't find something that relates a little more.

**Comment by mwernimont** [comment]
@lindsaycarr Gotta help me out with that, you guys know R a ton more than I

**Comment by jread-usgs** [comment]
I agree - and an easy way to do it is to expand on the icon w/ `Analyze`. So `Analyze with packages` would be the same icon but with a small difference. Maybe @lindsaycarr has ideas?

**Comment by mwernimont** [comment]
![intro-2](https://cloud.githubusercontent.com/assets/6390096/16990048/30f0809e-4e5c-11e6-96e8-41099a200f7c.jpg)

Ignore the microscope, thoughts on the bottom right?

**Comment by mwernimont** [comment]
![intro-2](https://cloud.githubusercontent.com/assets/6390096/16990560/05aff002-4e5e-11e6-9e02-e1ecfc4cfab1.jpg)

@lindsaycarr @jread-usgs Upper right? Too much?

**Comment by aappling-usgs** [comment]
hee hee! I love it

**Comment by lindsaycarr** [comment]
nailed it @mwernimont !

**Comment by lindsaycarr** [comment]
@mwernimont I think we wanted to keep the base R visualize one that lines/points icon (the ggplot2 one would be that but also include a background)

**Comment by mwernimont** [comment]
@lindsaycarr Alright I can make that switch.

**Comment by jread-usgs** [comment]
Make sure the two "analyze" magnifying glasses are the same. Looks like the one on the right is a different size/shape and in a different location:
![image](https://cloud.githubusercontent.com/assets/2349007/16994702/17861c56-4e6e-11e6-8872-2362381d4b3e.png)

**Comment by mwernimont** [comment]
Yeah, the got resized wrong in the mockup but will be the same size in the app

**Comment by ldecicco-USGS** [comment]
so....we getting these in a PR @mwernimont ?

**Comment by mwernimont** [comment]
@ldecicco-USGS Well was hoping to get them in myself but can't figure out how to do that, so can get them to you

**Comment by ldecicco-USGS** [comment]
I can do it...but if you want to try, the markdown files for each "post" look like this:
```
---
author: Jeffrey W. Hollister & Emily Read
date: 2016-07-07
slug: Explore
draft: True
title: D. Explore
menu:
---
```
you just need to add a line about image...so it would look like:

```
---
author: Jeffrey W. Hollister & Emily Read
date: 2016-07-07
slug: Explore
draft: True
title: D. Explore
menu:
image: static/Explore/iconD.png
---
```
....unless you tried that already...

**Comment by mwernimont** [comment]
I did not, but now that I have the blueprint I can do it! thank you

**Comment by mwernimont** [comment]
@ldecicco-USGS #29 PR merged, icons in place if I did it correctly, which I believe I did

**Comment by lindsaycarr** [comment]
@mwernimont can you change the last icon from OWI to USGS-R? Otherwise, these look awesome!!!

**Comment by mwernimont** [comment]
@lindsaycarr  #30 takes care of that
