### ISSUE TITLE
OWI banner needs to be swapped out

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/intro-curriculum#3]
At minimum, just take out the banner.
Better, swap in the USGS-R banner

**Comment by lindsaycarr** [comment]
@mwernimont how much effort would this be?

**Comment by mwernimont** [comment]
@ldecicco-USGS @lindsaycarr I'm confused, the USGS Banner needs to be swapped out? Or you using banner in a context I'm not latching onto?

**Comment by mwernimont** [comment]
What website or place are we looking at I guess is a good question to ask too? http://owi.usgs.gov/R/ or http://usgs-r.github.io/ or neither?

**Comment by lindsaycarr** [comment]
We want a new tab on owi.usgs.gov/R called `Intro R Curriculum` or `R Curriculum`. That would contain the stuff in this repo. Hoping to get an OWI-styled banner, but with the owi.usgs.gov/R tabs (rather than People, Products, etc). @ldecicco-USGS can weigh in here too
